Repository riz4d/Hacktoberfest23, pull requests merged in 2023-10, with the labels that each got.

#1 TopologicalSorting.py
  TopologicalSorting.py
Labels: hacktoberfest-accepted

#2 Rename TopologicalSorting.py to TopologicalSorting/TopologicalSorting.py
  TopologicalSorting/TopologicalSorting.py
Labels: hacktoberfest-accepted

#3 hacktoberfest23
  SecurePassGen/pass.py
Labels: hacktoberfest-accepted

#4 readme
  SecurePassGen/README.md
Labels: hacktoberfest-accepted, under-reviewing

#5 ytdl23
  yt-videodl/main.py
Labels: hacktoberfest-accepted

#6 requirements
  yt-videodl/requirements.txt
Labels: hacktoberfest-accepted

#7 docs
  yt-videodl/README.md
Labels: hacktoberfest-accepted

#8 added an wallpeper project
  wallpaper/images/for.gif
  wallpaper/images/icons8-download-48.png
  wallpaper/images/icons8-download-unscreen.gif
  wallpaper/images/icons8-left-30.png
  wallpaper/images/icons8-lively-wallpaper-48.png
  wallpaper/images/icons8-right-30.png
  wallpaper/images/icons8-right-unscreen.gif
  wallpaper/images/icons8-search-48.png
  wallpaper/images/load.gif
  wallpaper/index.html
  wallpaper/script.js
  wallpaper/style.css
Labels: hacktoberfest-accepted, under-reviewing

#9 Add files via upload
  PizzaHub/images/19-pizza-png-image.png
  PizzaHub/images/5-pizza-png-image.png
  PizzaHub/images/6-pizza-png-image.png
  PizzaHub/images/9-pizza-png-image.png
  PizzaHub/images/background.png
  PizzaHub/images/pngwing.com-removebg.png
  PizzaHub/images/pngwing.com.png
  PizzaHub/index.html
  PizzaHub/mediaqueries.css
  PizzaHub/style.css
Labels: hacktoberfest-accepted, under-reviewing

#10 LeetCode 135.Candy Solution in C++ using DP
  LeetCode 135.Candy Solution/C++Solution.cpp
Labels: hacktoberfest-accepted

#11 Basic calci, cube input range calci
  Calculator.cpp
  Range Cube calculator.py
Labels: hacktoberfest-accepted, under-reviewing

#12 Update and rename Calculator.cpp to Calculator/Calculator.cpp
  Calculator/Calculator.cpp
Labels: hacktoberfest-accepted

#16 Create Calculator_Using_Tkintor
  Calculator_Using_Tkintor
Labels: hacktoberfest-accepted

#21 Contributions in readme
  README.md
Labels: hacktoberfest-accepted

#22 C++ program to convert int to roman numerical
  Numericalconversion/inttoroman.cpp
Labels: hacktoberfest-accepted

#28 Added Network Usage Tracker in Python
  Network Usage Tracker/Images/1.jpg
  Network Usage Tracker/Images/2.jpg
  Network Usage Tracker/Images/3.jpg
  Network Usage Tracker/Images/4.jpg
  Network Usage Tracker/Images/5.jpg
  Network Usage Tracker/Images/6.jpg
  Network Usage Tracker/Images/7.jpg
  Network Usage Tracker/Images/8.jpg
  Network Usage Tracker/Images/front.png
  Network Usage Tracker/README.md
  Network Usage Tracker/network_usage_tracker.py
  Network Usage Tracker/requirements.txt
Labels: hacktoberfest-accepted

#27 Guess the number game
  GuessTheNumber/index.html
  GuessTheNumber/script.js
  GuessTheNumber/style.css
Labels: hacktoberfest-accepted

#26 added my project
  Calculator using javascript/index.html
  Calculator using javascript/script.js
  Calculator using javascript/style.css
Labels: hacktoberfest-accepted

#29 Create dsa.py
  dsa/dsa.py
Labels: hacktoberfest-accepted

#31 Added secrets project #30
  Secrets/.DS_Store
  Secrets/.gitignore
  Secrets/app.js
  Secrets/package-lock.json
  Secrets/package.json
  Secrets/public/css/bootstrap-social.css
  Secrets/public/css/styles.css
  Secrets/views/home.ejs
  Secrets/views/login.ejs
  Secrets/views/partials/footer.ejs
  Secrets/views/partials/header.ejs
  Secrets/views/register.ejs
  Secrets/views/secrets.ejs
  Secrets/views/submit.ejs
Labels: hacktoberfest-accepted

#33 Add:youtube id finder
  YouTube Video ID Finder/youtube_video_id_finder.html
Labels: hacktoberfest-accepted

#34 Stopwatch and timer Combined
  Stopwatch_and_Timer/beep.wav
  Stopwatch_and_Timer/index.html
  Stopwatch_and_Timer/newtimerscript.js
  Stopwatch_and_Timer/stopwatchscript.js
  Stopwatch_and_Timer/style.css
Labels: hacktoberfest-accepted

#35 added Random Quote Generator project
  GuessTheNumber/index.html
  Random Quote Generator/index.html
Labels: hacktoberfest-accepted

#39 I have added a new function to evaluate the power of any number in calculator.cpp file
  Calculator/Calculator.cpp
Labels: hacktoberfest-accepted

#40 flame calc
  flame_calculator/main.py
Labels: hacktoberfest-accepted

#41 hangman game
  hangman/main.py
  hangman/words.py
Labels: hacktoberfest-accepted

#42 add date validation algorithm
  Date_Validation/date.py
Labels: hacktoberfest-accepted

#43 Add files via upload
  NetflixClone/images/down-icon.png
  NetflixClone/images/feature-1.png
  NetflixClone/images/feature-2.png
  NetflixClone/images/feature-3.png
  NetflixClone/images/feature-4.png
  NetflixClone/images/header-image.png
  NetflixClone/images/logo.png
  NetflixClone/images/w.png
  NetflixClone/index.html
  NetflixClone/style.css
Labels: hacktoberfest-accepted

#44 modified random quote generator
  Random Quote Generator/index.html
Labels: hacktoberfest-accepted

#45 Added new files
  Random Quote Generator/app.js
  Random Quote Generator/images/favicon-32x32.png
  Random Quote Generator/images/icon-dice.svg
  Random Quote Generator/images/pattern-divider-desktop.svg
  Random Quote Generator/images/pattern-divider-mobile.svg
  Random Quote Generator/style.css
Labels: hacktoberfest-accepted

#46 Added mini game on python.
  Battle-Knights/import time, random.py
Labels: hacktoberfest-accepted

#47 Initial Commit
  Calculator/calc.py
Labels: hacktoberfest-accepted

#48 add new button in calculator
  Calculator/Add new button in calculator
Labels: hacktoberfest-accepted

#56 setup.py
  Battle-Knights/setup.py
Labels: enhancement

#54 process.py
  Battle-Knights/process.py
Labels: hacktoberfest-accepted

#57 states.py
  Battle-Knights/states.py
Labels: hacktoberfest-accepted

#52 move_details.py
  Battle-Knights/move_details.py
Labels: hacktoberfest-accepted

#59 ready
  leap_year/leap_year.py
Labels: hacktoberfest-accepted

#61 Added Palindrome code
  palindrome.py
Labels: hacktoberfest-accepted

#62 added snake-water-gun game
  Snake-Water-Gun/README.md
  Snake-Water-Gun/Snake_water_gun.js
Labels: hacktoberfest-accepted

#66 Create random-inspirational-quotes-generator.py
  random-inspirational-quotes-generator.py
Labels: hacktoberfest-accepted

#65 Create img_recog
  img_recog
Labels: hacktoberfest-accepted

#64 Create arnstrong.py
  arnstrong.py
Labels: hacktoberfest-accepted

#69 CDMA Project implemented in python
  CDMA/README.md
  CDMA/src/channel.py
  CDMA/src/const.py
  CDMA/src/gen_file.py
  CDMA/src/main.py
  CDMA/src/receiver.py
  CDMA/src/sender.py
  CDMA/src/textfiles/analysis.txt
  CDMA/src/textfiles/input/input1.txt
  CDMA/src/textfiles/input/input2.txt
  CDMA/src/textfiles/input/input3.txt
Labels: hacktoberfest-accepted

#68 Dictionary App Using Javascript Added
  Dictionary App using Javascript/.prettierrc
  Dictionary App using Javascript/index.html
  Dictionary App using Javascript/src/app.js
  Dictionary App using Javascript/src/style.css
Labels: hacktoberfest-accepted

#67 Added selection sort Algorithm in Python
  .gitignore
  dsa/selectionsort.py
Labels: hacktoberfest-accepted
